### ISSUE TITLE
src/main/resources/data.sql fehlende CREATE TABLES

### ISSUE THREAD

**Issue by LVGDDesman** [MaxDedecke/CSCSystem#1]
In src/main/resources/data.sql fehlen die Create Table ... Aufrufe.
Welche Änderungen müssen sonst noch an einer frischen DB-Installation gemacht werden? (abgesehen Nutzermanagement)

**Comment by MaxDedecke** [comment]
Kümmerst du dich drum oder soll ich die inserts schreiben ?

**Comment by LVGDDesman** [comment]
Ich übernehms, hab die auch schon fast fertig für die Demo

**Comment by MaxDedecke** [comment]
Sehr gut :)

**Comment by LVGDDesman** [comment]
ist im docker branch
